language: python
python:
  - '2.7'
env:
  - DJANGO=1.6.1 DB=postgres
install:
  - python setup.py install
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
before_script:
  - find . | grep .py$ | grep -v /migrations | xargs pep8 --max-line-length=120
  - find . | grep .py$ | grep -v /migrations | grep -v __init__.py | xargs pyflakes
script:
  - coverage run --source='entity' --branch --omit 'entity/migrations/*' manage.py test
  - coverage report --fail-under=100
